# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-06-05 16:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('benart', '0004_images_allimg'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(default=1111111, max_length=255),
            preserve_default=False,
        ),
    ]
