# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-06-05 17:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('benart', '0005_user_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='images',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
        migrations.DeleteModel(
            name='comment',
        ),
    ]
